stages:
- test
- build
- deploy

variables:
  IMAGE: registry.gitlab.com/bestdoctor/backend/its_on
  POSTGRES_PASSWORD: 'test123'
  DB_CONTAINER_NAME: pg-for-its_on-$CI_COMMIT_SHORT_SHA
  REDIS_CONTAINER_NAME: redis-for-its_on-$CI_COMMIT_SHORT_SHA

test:
  tags:
    - itson-tests
  stage: test
  before_script:
    - sudo docker run --rm -d
                      --name $DB_CONTAINER_NAME
                      -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD
                      --network tests_network
                      postgres:9.6
    - sudo docker run --rm -d
                      --name $REDIS_CONTAINER_NAME
                      --network tests_network
                      redis
  script:
    - sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - sudo docker build -t $IMAGE:$CI_COMMIT_SHORT_SHA .
    - sudo docker run --rm
                      -e DYNACONF_DATABASE__dsn=postgresql://postgres:$POSTGRES_PASSWORD@$DB_CONTAINER_NAME:5432/test_its_on
                      -e DYNACONF_DATABASE__superuser_dsn=postgresql://postgres:$POSTGRES_PASSWORD@$DB_CONTAINER_NAME:5432/postgres
                      -e DYNACONF_REDIS_URL=redis://$REDIS_CONTAINER_NAME:6379/1
                      --network tests_network
                      $IMAGE:$CI_COMMIT_SHORT_SHA test
  after_script:
    - sudo docker stop $DB_CONTAINER_NAME
    - sudo docker stop $REDIS_CONTAINER_NAME

build:
  tags:
    - itson-build
  stage: build
  script:
    - sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - sudo docker build -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:latest .
    - sudo docker push $IMAGE:$CI_COMMIT_SHORT_SHA
    - sudo docker push $IMAGE:latest
  only:
    refs:
      - master

deploy_production:
  stage: deploy
  when: manual
  allow_failure: false
  tags:
    - itson-deploy
  script:
    - ~/scm/deploy/run-deploy-its-on.sh -e "target=deploy commit_sha=$CI_COMMIT_SHORT_SHA registry_token=$CI_JOB_TOKEN"
  only:
    refs:
      - master

deploy_staging_int:
  stage: deploy
  when: manual
  allow_failure: false
  tags:
    - itson-deploy
  script:
    - ~/scm/deploy/run-deploy-staging-its-on.sh -l staging-int.bestdoctor.ru -e "target=deploy service=its_on commit_sha=$CI_COMMIT_SHORT_SHA registry_token=$CI_JOB_TOKEN"
  only:
    refs:
      - master

deploy_staging_ret:
  stage: deploy
  when: manual
  allow_failure: false
  tags:
    - itson-deploy
  script:
    - ~/scm/deploy/run-deploy-staging-its-on.sh -l staging-ret.bestdoctor.ru -e "target=deploy service=its_on commit_sha=$CI_COMMIT_SHORT_SHA registry_token=$CI_JOB_TOKEN"
  only:
    refs:
      - master

deploy_staging_qa:
  stage: deploy
  when: manual
  allow_failure: false
  tags:
    - itson-deploy
  script:
    - ~/scm/deploy/run-deploy-staging-its-on.sh -l staging-qa.bestdoctor.ru -e "target=deploy service=its_on commit_sha=$CI_COMMIT_SHORT_SHA registry_token=$CI_JOB_TOKEN"
  only:
    refs:
      - master

deploy_staging_med:
  stage: deploy
  when: manual
  allow_failure: false
  tags:
    - itson-deploy
  script:
    - ~/scm/deploy/run-deploy-staging-its-on.sh -l staging-med.bestdoctor.ru -e "target=deploy service=its_on commit_sha=$CI_COMMIT_SHORT_SHA registry_token=$CI_JOB_TOKEN"
  only:
    refs:
      - master
