default:
  debug: false
  host: localhost
  port: 8081
  database:
    dsn: postgresql://bestdoctor:bestdoctor@localhost:5432/its_on
  enable_db_logging: false
  cache_url: memory://
  cache_ttl: 300

development:
  environment: Dev
  debug: true
  enable_db_logging: true
  cache_ttl: 1

production:
  environment: Prod

staging:
  environment: Staging

testing:
  environment: Test
  database:
    dsn: postgresql://bestdoctor:bestdoctor@localhost:5432/test_its_on
    superuser_dsn: postgresql://bestdoctor:bestdoctor@localhost:5432/its_on
  cache_ttl: 0
